version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Estas credenciais seriam substituídas por um banco de dados de teste
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.H2Dialect
      SPRING_FLYWAY_BASELINEONMIGRATE: true
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_SECURITY_USER_NAME: test
      SPRING_SECURITY_USER_PASSWORD: test
      SERVER_ERROR_INCLUDE_MESSAGE: always
