name: Java CI with Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: mvn clean test

      - name: Build the Docker image
        run: docker build -t bluepoints:latest .

      - name: Test Docker image (basic check)
        run: |
          # Apenas verificamos se a imagem pode ser executada
          docker run --name test-container -d bluepoints:latest
          sleep 5
          # Exibe logs independente do resultado
          echo "Container logs:"
          docker logs test-container
          # Verifica status
          CONTAINER_RUNNING=$(docker inspect -f '{{.State.Running}}' test-container)
          echo "Container running: $CONTAINER_RUNNING"
          # Limpa
          docker stop test-container || true
          docker rm test-container

      # Simplificado, apenas para verificar se docker compose funciona
      - name: Test docker compose basic functionality
        run: |
          # Simplesmente tenta executar o comando, sem verificar o status
          docker compose -f docker-compose.ci.yml config
          echo "Docker compose configuration is valid"
