name: Java CI with Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: ./mvnw clean test

      - name: Build the Docker image
        run: docker build -t bluepoints:latest .

      - name: Test Docker image
        run: |
          docker run --name test-container -d bluepoints:latest
          # Aguarda alguns segundos para a aplicação iniciar
          sleep 10
          # Verifica se o container está em execução
          if [ "$(docker inspect -f '{{.State.Running}}' test-container)" != "true" ]; then
            echo "Container não está rodando!"
            docker logs test-container
            exit 1
          fi
          # Para e remove o container
          docker stop test-container
          docker rm test-container

      - name: Test with docker-compose CI configuration
        run: |
          # Inicia com a configuração CI
          docker-compose -f docker-compose.ci.yml up -d
          # Aguarda alguns segundos para a aplicação iniciar
          sleep 10
          # Verifica se o container está em execução
          if [ "$(docker inspect -f '{{.State.Running}}' bluepoints-fase6-01-app-1)" != "true" ]; then
            echo "Container do docker-compose não está rodando!"
            docker-compose -f docker-compose.ci.yml logs
            exit 1
          fi
          # Para e remove os containers
          docker-compose -f docker-compose.ci.yml down
